apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-deployment
  labels:
    app: ci-cd-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ci-cd-app
  template:
    metadata:
      labels:
        app: ci-cd-app
    spec:
      containers:
        - name: ci-cd-app-container
          image: natakravchenko/app-test:v2
          ports:
            - containerPort: 8080
