name: test
on: [workflow_dispatch]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - name: step 1
        run: ls -a
      - name: step 2
        run: uname
      - name: step 3
        run: |
          echo 'Hello world'
          echo 'Bye - bye'
          java -version
      - name: create java program
        run: |
          echo 'public class Hello { public static void main(String args[]) { System.out.println("Hello from Github action"); }}' >> Hello.java
          ls -a
          javac Hello.java
          ls -a
          java Hello
      - name: upload file
        uses: actions/upload-artifact@v4
        with:
           name: my-artifact
           path: ${{ github.workspace }}/Hello.java
  
